_wandb:
    value:
        cli_version: 0.26.1
        e:
            1timkygke3gnuhgoh00sa5uo56eilx9u:
                args:
                    - --wandb
                codePath: scripts/train_mpn.py
                codePathLocal: scripts/train_mpn.py
                cpu_count: 56
                cpu_count_logical: 112
                cudaVersion: "13.3"
                disk:
                    /:
                        total: "21407727616"
                        used: "10560921600"
                email: zihan16@uw.edu
                executable: /home/zihan.zhang/.conda/envs/mpn/bin/python
                git:
                    commit: cd622a733f3d9f0ffe303ec2783bd188a06b7007
                    remote: git@github.com:StevenZhang0116/mpn_local_learning.git
                gpu: NVIDIA A100-PCIE-40GB
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-3b55548f-cca3-e4e6-349f-5f98bcded86d
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-5a6194d9-6024-9790-2744-5457df15be65
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-960012eb-e4b4-e88f-3968-050c852c3c60
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-c3d2027f-0192-6c2e-c336-3c090899de4c
                host: n04
                memory:
                    total: "1081265594368"
                os: Linux-5.14.0-687.10.1.el9_8.0.1.x86_64-x86_64-with-glibc2.34
                program: /allen/programs/mindscope/workgroups/auto-model/zihan.zhang/mpn_local_learning/scripts/train_mpn.py
                python: CPython 3.9.23
                root: /allen/programs/mindscope/workgroups/auto-model/zihan.zhang/mpn_local_learning
                startedAt: "2026-07-20T20:09:11.961176Z"
                writerId: 1timkygke3gnuhgoh00sa5uo56eilx9u
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 15
                - 16
                - 61
            "4": 3.9.23
            "5": 0.26.1
            "12": 0.26.1
            "13": linux-x86_64
acc_label:
    value: angle accuracy (%)
arch_desc:
    value: arch=[1, 200, 200, 1]
arch_tag:
    value: ""
batch:
    value: 128
device:
    value: cuda
dtype:
    value: torch.float32
experiment:
    value: train_dmpn_contextdelaydm1_h200_b128_n5000_lr1e-03_exact_spatial_res_in-exact_eta1.00_lam0.99_runs2
feedback_mode:
    value: exact_spatial
file_prefix:
    value: train_dmpn
grad_clip:
    value: 10
input_mode:
    value: exact
input_normalize:
    value: false
lr:
    value: 0.001
metric:
    value: accuracy
mp_residual:
    value: true
n_datasets:
    value: 5000
n_hidden:
    value: 200
n_runs:
    value: 2
rule:
    value: local_exact_rowlocal
rules_to_run:
    value:
        - bptt
        - local_exact_rowlocal
        - local_diag_rflo
        - local_direct
ruleset:
    value: contextdelaydm1
run_idx:
    value: 0
seed:
    value: 1724781836
